name: Continuous Deploy on Merge

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@consorciei:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Fetching node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          scope: '@consorciei'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 